{% set name = "pyecharts" %}
{% set version = "2.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyecharts-{{ version }}.tar.gz
  sha256: 4d7f8dcbee1525a6eeecab589efcdbe939feee4c46930d90b2734bff04077ecc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - jinja2
    - prettytable
    - simplejson

test:
  imports:
    - pyecharts
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  description: 'Apache Echarts is easy-to-use, highly interactive and highly performant javascript visualization library under Apache license. Since its first public release in 2013, it now dominates over 74% of Chinese web front-end market. Yet Python is an expressive language and is loved by data science community. Combining
    the strength of both technologies, pyecharts is born.'
  dev_url: https://github.com/pyecharts/pyecharts
  doc_url: https://pyecharts.org/#/en-us/
  home: https://pyecharts.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python options, make charting easier

extra:
  recipe-maintainers:
    - rxm7706
